# Generated by Django 5.2.6 on 2025-10-03 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comercial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaPlanejamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "verbose_name": "Categoria de Planejamento",
                "verbose_name_plural": "Categorias de Planejamento",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="TarefaPlanejada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=150)),
                ("data_inicio_prevista", models.DateField()),
                ("data_fim_prevista", models.DateField()),
                ("data_fim_real", models.DateField(blank=True, null=True)),
                (
                    "custo_planejado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "custo_real",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="planejamento.categoriaplanejamento",
                    ),
                ),
                (
                    "empreendimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas_planejamento",
                        to="comercial.empreendimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarefa Planejada",
                "verbose_name_plural": "Tarefas Planejadas",
                "ordering": ("data_inicio_prevista",),
            },
        ),
    ]
