# Generated by Django 5.2.6 on 2025-10-03 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comercial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recebivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data_vencimento", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                (
                    "valor_pago",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Em aberto"),
                            ("pago", "Pago"),
                            ("atrasado", "Atrasado"),
                            ("renegociado", "Renegociado"),
                        ],
                        default="aberto",
                        max_length=15,
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcelas",
                        to="comercial.venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recebível",
                "verbose_name_plural": "Recebíveis",
                "ordering": ("data_vencimento",),
            },
        ),
    ]
