# Generated by Django 5.2.6 on 2025-10-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carteira", "0001_initial"),
        ("comercial", "0002_venda_comercial_v_data_ve_46a90f_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="recebivel",
            index=models.Index(
                fields=["data_vencimento"], name="carteira_re_data_ve_0e3ad6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recebivel",
            index=models.Index(fields=["status"], name="carteira_re_status_785c49_idx"),
        ),
    ]
