# Generated by Django 5.2.6 on 2025-10-03 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Corretor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Corretor",
                "verbose_name_plural": "Corretores",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="Empreendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=150)),
                ("cidade", models.CharField(max_length=80)),
                ("data_lancamento", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Empreendimento",
                "verbose_name_plural": "Empreendimentos",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cliente_nome", models.CharField(max_length=120)),
                ("data_venda", models.DateField()),
                ("unidades_vendidas", models.PositiveIntegerField(default=1)),
                (
                    "valor_contrato",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativa", "Ativa"),
                            ("cancelada", "Cancelada"),
                            ("concluida", "Concluída"),
                        ],
                        default="ativa",
                        max_length=15,
                    ),
                ),
                (
                    "corretor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendas",
                        to="comercial.corretor",
                    ),
                ),
                (
                    "empreendimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendas",
                        to="comercial.empreendimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas",
                "ordering": ("-data_venda",),
            },
        ),
    ]
