# Generated by Django 5.2.6 on 2025-10-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="venda",
            index=models.Index(
                fields=["data_venda"], name="comercial_v_data_ve_46a90f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venda",
            index=models.Index(
                fields=["empreendimento"], name="comercial_v_empreen_c00823_idx"
            ),
        ),
    ]
