# Generated by Django 5.2.6 on 2025-10-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0002_venda_comercial_v_data_ve_46a90f_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empreendimento",
            name="cidade",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]
