# Generated by Django 5.2.6 on 2025-10-03 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comercial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=120)),
                (
                    "documento",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="CNPJ/CPF"
                    ),
                ),
                ("contato", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="PedidoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data_pedido", models.DateField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("materiais", "Materiais"),
                            ("servicos", "Serviços"),
                            ("equipamentos", "Equipamentos"),
                            ("outros", "Outros"),
                        ],
                        max_length=20,
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "empreendimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_compra",
                        to="comercial.empreendimento",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="compras.fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Compra",
                "verbose_name_plural": "Pedidos de Compra",
                "ordering": ("-data_pedido",),
            },
        ),
        migrations.CreateModel(
            name="ItemCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("descricao", models.CharField(max_length=200)),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "custo_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="compras.pedidocompra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Compra",
                "verbose_name_plural": "Itens de Compra",
            },
        ),
    ]
