# Generated by Django 5.2.6 on 2025-10-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0002_venda_comercial_v_data_ve_46a90f_idx_and_more"),
        ("compras", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pedidocompra",
            index=models.Index(
                fields=["empreendimento"], name="compras_ped_empreen_d0326d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pedidocompra",
            index=models.Index(
                fields=["fornecedor"], name="compras_ped_fornece_489c67_idx"
            ),
        ),
    ]
